#!/bin/sh

lb config noauto \
--cache true \
--apt-recommends true \
--architectures amd64 \
--debian-installer live \
--linux-flavours amd64 \
--mode debian \
--archive-areas "main contrib non-free" \
--binary-images iso-hybrid \
--system live \
--security true \
--win32-loader false \
--distribution stretch \
--updates true \
--bootappend-live "boot=live components username=thirstyice" \
"${@}"
