#!/bin/sh

lb config noauto \
--cache true \
--apt-recommends true \
--architectures i386 \
--debian-installer false \
--linux-flavours 486 \
--mode debian \
--archive-areas "main contrib non-free" \
--binary-images iso-hybrid \
--system live \
--security true \
--win32-loader false \
--distribution jessie \
--updates true \
--bootappend-live "boot=live components username=thirstyice" \
"${@}"
